name: Update WinGet Packages

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *' # Scheduled to run daily at 03:00

env:
  KOMAC_VERSION: 1.11.0

jobs:
  update:
    name: Update package ${{ matrix.id }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
          - id: "Typst.Typst"
            repo: "typst/typst"
            url: "https://github.com/typst/typst/releases/download/v{VERSION}/typst-x86_64-pc-windows-msvc.zip"
          - id: "Casey.Just"
            repo: "casey/just"
            url: "https://github.com/casey/just/releases/download/{VERSION}/just-{VERSION}-x86_64-pc-windows-msvc.zip"
          - id: "michidk.vscli"
            repo: "michidk/vscli"
            url: "https://github.com/michidk/vscli/releases/download/v{VERSION}/vscli-x86_64-pc-windows-msvc.zip"

    steps:
    - name: Update Packages
      uses: michidk/winget-updater@latest
      with:
        komac-token: ${{ secrets.KOMAC_TOKEN }}
        package-id: ${{ matrix.id }}
        repo: ${{ matrix.repo }}
        url: ${{ matrix.url }}

  cleanup:
    name: Cleanup branches
    needs: update # Not necessarily needed as PRs don't get closed that quick but still nice to have it in order
    runs-on: ubuntu-22.04

    steps:
    - name: Run Komac
      uses: michidk/run-komac@latest
      with:
        args: 'branch cleanup --token=${{ secrets.KOMAC_TOKEN }}'
