name: Update winget packages

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *' # Scheduled to run daily at 03:00

env:
  KOMAC_VERSION: 1.11.0

jobs:
  update:
    name: Update package ${{ matrix.id }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - id: "Typst.Typst"
            repo: "typst/typst"
            url: "https://github.com/typst/typst/releases/download/v{VERSION}/typst-x86_64-pc-windows-msvc.zip"
          - id: "Casey.Just"
            repo: "casey/just"
            url: "https://github.com/casey/just/releases/download/{VERSION}/just-{VERSION}-x86_64-pc-windows-msvc.zip"
          - id: "michidk.vscli"
            repo: "michidk/vscli"
            url: "https://github.com/michidk/vscli/releases/download/v{VERSION}/vscli-x86_64-pc-windows-msvc.zip"

    steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install Komac
      run: wget https://github.com/russellbanks/Komac/releases/download/v${{ env.KOMAC_VERSION }}/Komac-${{ env.KOMAC_VERSION }}-all.jar -O komac.jar

    - name: Detect Latest Release
      uses: actions/github-script@v5
      id: latest_release
      with:
        script: |
          const [owner, repo] = '${{ matrix.config.repo }}'.split('/');
          const { data } = await github.repos.getLatestRelease({ owner, repo });
          const tagName = data.tag_name.startsWith('v') ? data.tag_name.substring(1) : data.tag_name;
          return tagName;

    - name: Update package
      run: |
        VERSION=${{ steps.latest_release.outputs.result }}
        URL=${{ matrix.url }}
        FINAL_URL=$(echo $URL | sed "s/\{VERSION}/$VERSION/g")
        java -jar komac.jar update --id=${{ matrix.id }} --version $VERSION --url $FINAL_URL --submit --token=${{ secrets.KOMAC_TOKEN }} || true

  cleanup:
    name: Cleanup branches
    needs: update # Not necessarily needed as PRs don't get closed that quick but still nice to have it in order
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install Komac
      run: wget https://github.com/russellbanks/Komac/releases/download/v${{ env.KOMAC_VERSION }}/Komac-${{ env.KOMAC_VERSION }}-all.jar -O komac.jar

    - name: Cleanup branches
      run: java -jar komac.jar branch cleanup --token=${{ secrets.KOMAC_TOKEN }}